/**
 * Versioned airline catalog used to normalize code-only provider responses.
 * Snapshot: 2026-07-12. Baseline: current IATA member list (360 unique codes),
 * overlaid with the project's curated catalog for commercial display names and
 * non-member carriers already supported by Emilia (383 unique codes total).
 */
export const AIRLINE_NAMES_BY_IATA: Readonly<Record<string, string>> = {
  '2A': 'Air Astra',
  '2K': 'Avianca Ecuador',
  '2L': 'Helvetic Airways',
  '2P': 'PAL Express',
  '2S': 'Southwind Airlines',
  '2W': 'World2Fly',
  '2Z': 'Voepass',
  '3E': 'Electra Airways',
  '3U': 'Sichuan Airlines',
  '3V': 'ASL Airlines Belgium',
  '4C': 'LATAM Airlines Colombia',
  '4M': 'Mavi Gök Airlines (MGA)',
  '4O': 'Air Montenegro',
  '4S': 'Red Sea Airlines',
  '4X': 'Avion Express Malta',
  '4Y': 'Discover Airlines',
  '4Z': 'Airlink',
  '5C': 'Challenge Airlines (IL)',
  '5D': 'Aeroméxico Connect',
  '5F': 'FLYONE',
  '5H': 'ASL Airlines Ireland',
  '5J': 'Cebu Pacific',
  '5N': 'Smartavia',
  '5O': 'ASL Airlines France',
  '5U': 'TAG Airlines',
  '5X': 'UPS Airlines',
  '5Y': 'Atlas Air',
  '5Z': 'CemAir',
  '6E': 'IndiGo',
  '6H': 'Israir',
  '6O': 'Iberojet',
  '6Y': 'SmartWings',
  '7C': 'Jeju Air',
  '7H': 'New Pacific Airlines',
  '7L': 'Silk Way West Airlines',
  '7R': 'RusLine',
  '8L': 'Lucky Air',
  '8M': 'Myanmar Airways International',
  '8R': 'Amelia',
  '9C': 'Spring Airlines',
  '9H': 'Air Changan',
  'A3': 'Aegean Airlines',
  'A9': 'Georgian Airways',
  'AA': 'American Airlines',
  'AC': 'Air Canada',
  'AD': 'Azul Brazilian Airlines',
  'AE': 'Mandarin Airlines',
  'AF': 'Air France',
  'AH': 'Air Algérie',
  'AI': 'Air India',
  'AK': 'AirAsia',
  'AM': 'Aeroméxico',
  'AP': 'Albastar',
  'AR': 'Aerolíneas Argentinas',
  'AS': 'Alaska Airlines',
  'AT': 'Royal Air Maroc',
  'AV': 'Avianca',
  'AW': 'Africa World Airlines',
  'AY': 'Finnair',
  'AZ': 'ITA Airways',
  'B0': 'La Compagnie',
  'B2': 'Belavia Belarusian Airlines',
  'B5': 'BBN Airlines',
  'B6': 'JetBlue Airways',
  'B7': 'UNI AIR',
  'B9': 'Iran Airtour Airline',
  'BA': 'British Airways',
  'BF': 'French Bee',
  'BG': 'Biman Bangladesh Airlines',
  'BI': 'Royal Brunei',
  'BJ': 'Nouvelair',
  'BK': 'Okay Airways',
  'BP': 'Air Botswana',
  'BR': 'EVA Air',
  'BS': 'US-Bangla Airlines',
  'BT': 'airBaltic',
  'BW': 'Caribbean Airlines',
  'BZ': 'Blue Bird Airways',
  'CA': 'Air China',
  'CC': 'Air Atlanta Icelandic',
  'CE': 'Chalair',
  'CF': 'China Postal Airlines',
  'CI': 'China Airlines',
  'CK': 'China Cargo Airlines',
  'CL': 'Lufthansa CityLine',
  'CM': 'Copa Airlines',
  'CS': 'Chair Airlines',
  'CU': 'Cubana',
  'CV': 'Cargolux',
  'CX': 'Cathay Pacific',
  'CY': 'Cyprus Airways',
  'CZ': 'China Southern',
  'D0': 'DHL Air',
  'D4': 'Airline GEO SKY',
  'D7': 'AirAsia X',
  'DD': 'Nok Air',
  'DE': 'Condor',
  'DL': 'Delta Air Lines',
  'DM': 'Arajet',
  'DN': 'DAN AIR',
  'DR': 'Ruili Airlines',
  'DT': 'TAAG Angola Airlines',
  'DV': 'SCAT Airlines',
  'E7': 'Estafeta Cargo',
  'E9': 'Iberojet Airlines',
  'EB': 'Wamos Air',
  'EI': 'Aer Lingus',
  'EK': 'Emirates',
  'EN': 'Air Dolomiti',
  'EO': 'Ikar',
  'EP': 'Iran Aseman Airlines',
  'ET': 'Ethiopian Airlines',
  'EU': 'Chengdu Airlines',
  'EW': 'Eurowings',
  'EY': 'Etihad Airways',
  'F3': 'flyadeal',
  'F9': 'Frontier Airlines',
  'FA': 'Safair',
  'FB': 'Bulgaria Air',
  'FC': 'Link Airways',
  'FD': 'Thai AirAsia',
  'FH': 'Freebird Airlines',
  'FI': 'Icelandair',
  'FJ': 'Fiji Airways',
  'FM': 'Shanghai Airlines',
  'FN': 'Fastjet Zimbabwe',
  'FR': 'Ryanair',
  'FU': 'Fuzhou Airlines',
  'FV': 'Rossiya Airlines',
  'FX': 'FedEx Express',
  'FZ': 'flydubai',
  'G3': 'Gol',
  'G4': 'Allegiant Air',
  'G5': 'China Express Airlines',
  'G6': 'GlobalX',
  'G9': 'Air Arabia',
  'GA': 'Garuda Indonesia',
  'GB': 'ABX Air',
  'GE': 'Global Airways and Lift',
  'GF': 'Gulf Air',
  'GJ': 'Loong Air',
  'GL': 'Air Greenland',
  'GP': 'APG Airlines',
  'GQ': 'Sky express',
  'GS': 'Tianjin Airlines',
  'GT': 'Air Guilin',
  'GX': 'GX Airlines',
  'H2': 'Sky Airline',
  'H3': 'Hello Jets',
  'H9': 'Himalaya Airlines',
  'HA': 'Hawaiian Airlines',
  'HB': 'Greater Bay Airlines',
  'HC': 'Air Senegal',
  'HF': 'Air Côte d\'Ivoire',
  'HM': 'Air Seychelles',
  'HO': 'Juneyao Airlines',
  'HP': 'PopulAir',
  'HU': 'Hainan Airlines',
  'HX': 'Hong Kong Airlines',
  'HY': 'Uzbekistan Airways',
  'I2': 'Iberia Express',
  'IB': 'Iberia',
  'ID': 'Batik Air',
  'IE': 'Solomon Airlines',
  'IF': 'Fly Baghdad',
  'IG': 'Air Italy',
  'IQ': 'Qazaq Air',
  'IR': 'Iran Air',
  'IX': 'Air India Express',
  'IZ': 'Arkia Israeli Airlines',
  'J2': 'Azerbaijan Airlines',
  'J4': 'Badr Airlines',
  'J6': 'JetSMART Colombia',
  'J7': 'FlyGabon',
  'J9': 'Jazeera Airways',
  'JA': 'JetSMART',
  'JD': 'Capital Airlines',
  'JG': 'JD Airlines',
  'JJ': 'LATAM Airlines Brasil',
  'JL': 'Japan Airlines',
  'JQ': 'Jetstar',
  'JS': 'Air Koryo',
  'JT': 'Lion Air',
  'JU': 'Air Serbia',
  'JX': 'STARLUX Airlines',
  'JZ': 'JetSMART Peru',
  'K6': 'Air Cambodia',
  'KC': 'Air Astana',
  'KE': 'Korean Air',
  'KJ': 'AIRZETA',
  'KL': 'KLM',
  'KM': 'KM Malta Airlines',
  'KN': 'China United Airlines',
  'KP': 'ASKY',
  'KQ': 'Kenya Airways',
  'KU': 'Kuwait Airways',
  'KY': 'Kunming Airlines',
  'KZ': 'Nippon Cargo Airlines',
  'L6': 'Mauritania Airlines International',
  'LA': 'LATAM Airlines',
  'LD': 'Air Hong Kong',
  'LG': 'Luxair',
  'LH': 'Lufthansa',
  'LJ': 'Jin Air',
  'LM': 'Loganair',
  'LO': 'LOT Polish Airlines',
  'LP': 'LATAM Airlines Peru',
  'LR': 'Avianca Costa Rica',
  'LX': 'Swiss International Air Lines',
  'LY': 'El Al Israel Airlines',
  'M0': 'Aero Mongolia',
  'M3': 'LATAM Cargo Brasil',
  'M4': 'Poste Air Cargo',
  'M7': 'MasAir',
  'MB': 'MNG Airlines',
  'MD': 'Madagascar Airlines',
  'ME': 'Middle East Airlines',
  'MF': 'Xiamen Airlines',
  'MH': 'Malaysia Airlines',
  'MK': 'Air Mauritius',
  'MP': 'Martinair Cargo',
  'MS': 'EgyptAir',
  'MU': 'China Eastern',
  'N4': 'Nordwind Airlines',
  'N7': 'Norra',
  'N8': 'National Airlines',
  'NE': 'Nesma Airlines',
  'NF': 'Air Vanuatu',
  'NH': 'All Nippon Airways',
  'NK': 'Spirit Airlines',
  'NO': 'Neos',
  'NP': 'Nile Air',
  'NS': 'Hebei Airlines',
  'NT': 'Binter Canarias',
  'NU': 'Japan Transocean Air',
  'NX': 'Air Macau',
  'NZ': 'Air New Zealand',
  'O3': 'SF Airlines',
  'OA': 'Olympic Air',
  'OB': 'Boliviana de Aviación',
  'OD': 'Batik Air Malaysia',
  'OF': 'Overland Airways',
  'OK': 'Czech Airlines',
  'OM': 'MIAT Mongolian Airlines',
  'ON': 'Nauru Airlines',
  'OS': 'Austrian Airlines',
  'OU': 'Croatia Airlines',
  'OV': 'Salam Air',
  'OZ': 'Asiana Airlines',
  'P0': 'Proflight Zambia',
  'P4': 'Air Peace',
  'P5': 'Wingo',
  'P6': 'Privilege Style',
  'PC': 'Pegasus Airlines',
  'PD': 'Porter Airlines',
  'PG': 'Bangkok Airways',
  'PK': 'Pakistan International Airlines',
  'PN': 'West Air',
  'PO': 'Polar Air Cargo',
  'PQ': 'SkyUp Airlines',
  'PR': 'Philippine Airlines',
  'PU': 'Plus Ultra',
  'PW': 'Precision Air',
  'PX': 'Air Niugini',
  'PZ': 'LATAM Paraguay',
  'QC': 'Camair-Co',
  'QF': 'Qantas',
  'QG': 'Citilink',
  'QH': 'Bamboo Airways',
  'QI': 'Ibom Air',
  'QP': 'Akasa Air',
  'QR': 'Qatar Airways',
  'QS': 'Smartwings',
  'QV': 'Lao Airlines',
  'QW': 'Qingdao Airlines',
  'QY': 'European Air Transport',
  'QZ': 'Indonesia AirAsia',
  'R5': 'Jordan Aviation',
  'RB': 'Syrianair',
  'RC': 'Atlantic Airways',
  'RE': 'Airhub Airlines',
  'RH': 'Hong Kong Air Cargo',
  'RJ': 'Royal Jordanian',
  'RO': 'TAROM',
  'RQ': 'Kam Air',
  'RX': 'Riyadh Air',
  'S4': 'Azores Airlines',
  'S7': 'S7 Airlines',
  'SA': 'South African Airways',
  'SB': 'Aircalin',
  'SC': 'Shandong Airlines',
  'SF': 'Domestic Airlines',
  'SG': 'SpiceJet',
  'SK': 'SAS Scandinavian Airlines',
  'SL': 'Thai Lion Air',
  'SM': 'Air Cairo',
  'SN': 'Brussels Airlines',
  'SP': 'SATA Air Acores',
  'SQ': 'Singapore Airlines',
  'SS': 'Corsair International',
  'SU': 'Aeroflot',
  'SV': 'Saudia',
  'SY': 'Sun Country Airlines',
  'SZ': 'Somon Air',
  'T0': 'Avianca Argentina',
  'TA': 'TACA',
  'TC': 'Air Tanzania',
  'TG': 'Thai Airways',
  'TK': 'Turkish Airlines',
  'TM': 'LAM',
  'TN': 'Air Tahiti Nui',
  'TP': 'TAP Air Portugal',
  'TR': 'Scoot',
  'TS': 'Air Transat',
  'TU': 'Tunisair',
  'TV': 'Xizang Airlines',
  'TW': 'Trinity Airways',
  'TX': 'Air Caraibes',
  'TY': 'Air Caledonie',
  'U2': 'easyJet',
  'U6': 'Ural Airlines',
  'U8': 'TUS Airways',
  'UA': 'United Airlines',
  'UB': 'Myanmar National Airlines',
  'UC': 'LATAM Cargo Chile',
  'UF': 'PAS',
  'UJ': 'AlMasria Universal Airlines',
  'UK': 'Vistara',
  'UL': 'SriLankan Airlines',
  'UN': 'United Nigeria Airlines',
  'UO': 'Hong Kong Express Airways',
  'UP': 'Bahamasair',
  'UQ': 'Urumqi Air',
  'UT': 'UTair',
  'UU': 'Air Austral',
  'UX': 'Air Europa',
  'V3': 'Carpatair',
  'V7': 'Volotea',
  'VA': 'Virgin Australia',
  'VE': 'Clic Air',
  'VF': 'AJet',
  'VJ': 'Vietjet',
  'VL': 'Lufthansa City Airlines',
  'VN': 'Vietnam Airlines',
  'VS': 'Virgin Atlantic',
  'VT': 'Air Tahiti',
  'VY': 'Vueling',
  'W2': 'FlexFlight',
  'W6': 'Wizz Air',
  'W8': 'Cargojet Airways',
  'WB': 'RwandAir',
  'WF': 'Wideroe',
  'WG': 'Sunwing Airlines',
  'WI': 'White coloured by you',
  'WJ': 'JetSMART Argentina',
  'WK': 'Edelweiss Air',
  'WN': 'Southwest Airlines',
  'WS': 'WestJet',
  'WT': 'Swiftair',
  'WV': 'Fly Namibia',
  'WX': 'CityJet',
  'WY': 'Oman Air',
  'X3': 'TUIfly',
  'X7': 'Challenge Airlines (BE)',
  'X9': 'Avion Express',
  'XC': 'Corendon Airlines',
  'XK': 'Air Corsica',
  'XL': 'LATAM Airlines Ecuador',
  'XQ': 'SunExpress',
  'XY': 'Flynas',
  'XZ': 'Aeroitalia',
  'Y4': 'Volaris',
  'Y7': 'NordStar',
  'Y8': 'Suparna Airlines',
  'YG': 'YTO Cargo Airlines',
  'YP': 'Air Premia',
  'YU': 'EuroAtlantic Airways',
  'YW': 'Air Nostrum',
  'Z2': 'Philippines AirAsia',
  'ZE': 'Eastar Jet',
  'ZH': 'Shenzhen Airlines',
  'ZP': 'Paranair',
  'ZQ': 'German Airways',
};

export const AIRLINE_CATALOG_SIZE = Object.keys(AIRLINE_NAMES_BY_IATA).length;
