// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import Cookies from 'js-cookie';
import type { Database } from './types';
import { COOKIE_DOMAIN } from '@/lib/host';

const SUPABASE_URL = "https://ujigyazketblwlzcomve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaWd5YXprZXRibHdsemNvbXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODk2MTEsImV4cCI6MjA3MjM2NTYxMX0.X6YvJfgQnCAzFXa37nli47yQxuRG-7WJnJeIDrqg5EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const CHUNK_SIZE = 3500;

function cookieAttrs(): Cookies.CookieAttributes {
  return {
    domain: COOKIE_DOMAIN,
    path: '/',
    sameSite: 'lax',
    secure: typeof window !== 'undefined' && window.location.protocol === 'https:',
    expires: 30,
  };
}

function readChunked(key: string): string | null {
  const all = Cookies.get();
  const direct = all[key];
  if (direct !== undefined) return direct;
  const parts: string[] = [];
  let i = 0;
  while (all[`${key}.${i}`] !== undefined) {
    parts.push(all[`${key}.${i}`]);
    i++;
  }
  return parts.length > 0 ? parts.join('') : null;
}

function removeChunked(key: string): void {
  const attrs = { domain: COOKIE_DOMAIN, path: '/' };
  Cookies.remove(key, attrs);
  const all = Cookies.get();
  let i = 0;
  while (all[`${key}.${i}`] !== undefined) {
    Cookies.remove(`${key}.${i}`, attrs);
    i++;
  }
}

function writeChunked(key: string, value: string): void {
  removeChunked(key);
  const attrs = cookieAttrs();
  if (value.length <= CHUNK_SIZE) {
    Cookies.set(key, value, attrs);
    return;
  }
  let i = 0;
  for (let offset = 0; offset < value.length; offset += CHUNK_SIZE) {
    Cookies.set(`${key}.${i}`, value.slice(offset, offset + CHUNK_SIZE), attrs);
    i++;
  }
}

const cookieStorage = {
  getItem: (key: string) => readChunked(key),
  setItem: (key: string, value: string) => writeChunked(key, value),
  removeItem: (key: string) => removeChunked(key),
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'sb-vibook-auth',
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    },
    // Optimized reconnection strategy
    timeout: 30000,
    heartbeatIntervalMs: 30000,
  }
});
